### ISSUE TITLE
Extract ocrd manager specific configuration

### ISSUE THREAD

**Issue by SvenMarcus** [slub/kitodo-production-docker#9]
Currently there is configuration for the communication with the OCRD manager in `startup.sh`, even though this repository is exclusively about providing a Kitodo Production container.
This makes for poor separation of concerns as one has to edit the content of submodules in `kitodo_production_ocrd` when communication details between the manager and Kitodo change and then update the main git repository accordingly.
OCRD manager specific configuration (ssh keys and so on) should therefore be extracted from this repository into `kitodo_production_ocrd`.

**Comment by markusweigelt** [comment]
Move the OCR-D Manager specific configuration to the [ocrd_kitodo](https://github.com/slub/ocrd_kitodo) with pr https://github.com/slub/ocrd_kitodo/pull/69
